#!/usr/bin/env node

// Generated by CoffeeScript 1.10.0
(function() {
  var callback, output, path, wave;

  wave = require('./wave');

  path = void 0;

  output = void 0;

  process.argv.forEach(function(val, index, array) {
    if (index === 2) {
      path = val;
    }
    if (index === 3) {
      return output = val;
    }
  });

  callback = function() {
    return console.log('Done.');
  };

  wave(path, output, callback);

}).call(this);
