// Generated by CoffeeScript 1.10.0
(function() {
  var HTMLSource, commands, compileFile, fs, outputPath, path, saveOutput, stopWith, vars;

  fs = require('fs');

  vars = {};

  commands = {
    callVariable: /<!-- \.(\w+) -->/i,
    includeFile: /<!-- \.include (.+) -->/i,
    fetchDeclaredVariableName: /<!-- ~(\w+)/i,
    declareVariableCommand: /<!-- ~(.)+( )(.)+ -->/i
  };

  HTMLSource = (function() {
    function HTMLSource(path1) {
      this.path = path1;
      this.lines = [];
    }

    HTMLSource.prototype.detectDeclareVariable = function(line) {
      var cmnd, data, name;
      if (commands.declareVariableCommand.test(line)) {
        cmnd = line.match(commands.declareVariableCommand)[0];
        name = cmnd.match(commands.fetchDeclaredVariableName)[1];
        data = cmnd.substring(6 + name.length, cmnd.length - 3).trim();
        vars[name] = data;
      }
      return line;
    };

    HTMLSource.prototype.detectCallVariable = function(line) {
      var name;
      if (commands.callVariable.test(line)) {
        name = line.match(commands.callVariable)[1];
        line = line.replace(commands.callVariable, vars[name]);
      }
      return line;
    };

    HTMLSource.prototype.detectIncludeFile = function(line) {
      var component, i, len, ref, source;
      if (commands.includeFile.test(line)) {
        source = line.match(commands.includeFile)[1];
        component = new HTMLSource(source);
        component.parse();
        ref = component.lines;
        for (i = 0, len = ref.length; i < len; i++) {
          line = ref[i];
          this.lines.push(line);
        }
      }
      return line;
    };

    HTMLSource.prototype.formatLine = function(line) {
      line = this.detectDeclareVariable(line);
      line = this.detectCallVariable(line);
      line = this.detectIncludeFile(line);
      return this.lines.push(line);
    };

    HTMLSource.prototype.parse = function() {
      var data, i, len, line, ref, results;
      data = fs.readFileSync(this.path, 'utf-8');
      ref = data.split(/\r?\n/i);
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        line = ref[i];
        results.push(this.formatLine(line));
      }
      return results;
    };

    return HTMLSource;

  })();

  stopWith = function(error) {
    console.log('Stopped with error: ' + error);
    return process.exit();
  };

  saveOutput = function(output) {
    var outputFile;
    outputFile = fs.createWriteStream(outputPath);
    output.forEach(function(v) {
      return outputFile.write(v + '\n');
    });
    return outputFile.end();
  };

  compileFile = function(file) {
    var html;
    html = new HTMLSource(file);
    html.parse();
    return saveOutput(html.lines);
  };

  path = 'error.error';

  outputPath = 'output.html';

  process.argv.forEach(function(val, index, array) {
    if (index === 2) {
      path = val;
    }
    if (index === 3) {
      return outputPath = val;
    }
  });

  fs.lstat(path, function(error, stats) {
    if (error) {
      stopWith(error);
    }
    if (stats.isFile()) {
      return compileFile(path);
    }
  });

}).call(this);
